apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-app
  labels:
    app: simple-web-app
spec:
  selector:
    matchLabels:
      app: simple-web-app
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: simple-web-app
    spec:
      containers:
      - name: simple-web-app
        image: gcr.io/product-catalog-237219/simple-web-app
        ports:
        - containerPort: 8000
